spring:
  application:
    name: ead-course-service          # Utilizar mesmo nome para config server .yaml
  config:                               # configuração de conexão com config server
    import: 'configserver:'
  #    import: 'optional:configserver:'   # Utilizar a opção: optional para caso o config server estiver fora carregara as configurações locais do microservice
  cloud:                                # Localizar o config server com a nomeclatura especifica
    config:
      discovery:
        serviceId: ead-config-server
      # credencias para acessar config-server com a implementação de spring-security
      username: configserver
      password: 'ead123cs'